// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalContractsAPI.Context;

#nullable disable

namespace RentalContractsAPI.Migrations
{
    [DbContext(typeof(RentalContractsContext))]
    [Migration("20230228110807_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentalContractsAPI.Models.EquipmentPlacementContract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContractID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int>("NumOfUnits")
                        .HasColumnType("int");

                    b.Property<int>("ProductionPremisesCode")
                        .HasColumnType("int");

                    b.Property<int>("TechnologyEquipmentTypeCode")
                        .HasColumnType("int");

                    b.HasKey("ContractId")
                        .HasName("PK__Equipmen__C90D340964F19D7A");

                    b.ToTable("EquipmentPlacementContract", (string)null);
                });

            modelBuilder.Entity("RentalContractsAPI.Models.ProductionPremise", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .UseCollation("SQL_Ukrainian_CP1251_CI_AS");

                    b.Property<decimal>("RegulatoryArea")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Code")
                        .HasName("PK__Producti__A25C5AA6013D0B85");

                    b.ToTable("ProductionPremises");
                });

            modelBuilder.Entity("RentalContractsAPI.Models.TechnologyEquipmentType", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .UseCollation("SQL_Ukrainian_CP1251_CI_AS");

                    b.HasKey("Code")
                        .HasName("PK__Technolo__A25C5AA641CFED7E");

                    b.ToTable("TechnologyEquipmentType", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
